name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get-Code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Maven
        run: sudo apt-get install -y maven
      - name: Install Maven dependencies
        run: mvn dependency:resolve
      - name: Run Maven clean and package
        run: mvn clean package
      - name: Uploading War file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: War File
          path: target/angular11-spring-boot2-mysql-0.0.1-SNAPSHOT.war
      - name: Test with Maven
        run: mvn test


